#!/bin/bash

VALUE=$(amixer -c 0 contents | \
awk -F"," '
$1 == "numid=15" {
    c=1
} c && /: values/ {
   split($0, a, "=")
   print a[2];
   exit
}')

if [[ "${VALUE}" == "on" ]]; then
	device="Headphone"
else
	device="Master"
fi

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	pactl set-sink-volume @DEFAULT_SINK@ +5%
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  amixer -q sset ${device} toggle
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	pactl set-sink-volume @DEFAULT_SINK@ -5%
fi


statusLine=$(amixer get "${device}" | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$( pamixer --get-volume)

if [[ "${VALUE}" == "on" ]]; then
	if [[ "${status}" == "on" ]]; then
		echo "" "${volume}%"
		echo "" "${volume}%"
	else
		echo " mute"
		echo " mute"
	fi
else 
	if [[ "${status}" == "on" ]]; then
		echo "" "${volume}%"
		echo "" "${volume}%"
	else
		echo " mute"
		echo " mute"
	fi
fi

