#!/bin/sh

RawInfromation=$(acpi | head -n 1)
Status=$(echo "${RawInfromation}" | awk -F ' ' '{print $3}' | tr -d ',')
Battery=$(echo "${RawInfromation}" | awk -F ' ' '{print $4}' | tr -d ',%')

Charging=""
Connect=""
PercentFull=""
Percent4=""
Percent3=""
Percent2=""
Percent1=""

if [[ "${Battery}" -lt "10" ]]; then
	Icon=$Percent1
elif [[ "${Battery}" -lt "30" ]]; then
	Icon=$Percent2
elif [[ "${Battery}" -lt "60" ]]; then
	Icon=$Percent3
elif [[ "${Battery}" -lt "85" ]]; then
	Icon=$Percent4
else
	Icon=$PercentFull
fi

if [[ "${Status}" == "Full" ]]; then
	echo "${Connect} ${Battery}%"
	echo "${Connect} ${Battery}%"
elif [[ "${Status}" == "Charging" ]]; then
	echo "${Charging} ${Icon} ${Battery}%"
	echo "${Charging} ${Icon} ${Battery}%"
else
	echo "${Icon} ${Battery}%"
	echo "${Icon} ${Battery}%"
fi
