#! /bin/sh
# Based on http://openweathermap.org/current

API_KEY="2f06a5cb832eca21f9e07614f49cc056"

## Check on http://openweathermap.org/find
CITY_ID="1792947"

URGENT_LOWER=0
URGENT_HIGHER=30

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""
ICON_DUST=""

SYMBOL_CELSIUS="°C"


WEATHER_URL="https://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"
#WEATHER_URL='http://api.openweathermap.org/data/2.5/weather\?id\=1792947\&appid\=2f06a5cb832eca21f9e07614f49cc056'

WEATHER_INFO=$(wget -qO- ${WEATHER_URL})
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '"main":"[a-Z]*"' | awk -F ':' '{print $2}' | tr -d '"' | sed -n '1p')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '"temp":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

#WEATHER_MAIN="Rain"
#echo "$WEATHER_TEMP"
#echo "$WEATHER_MAIN"

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Clouds* ]]; then
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Dust* ]]; then
  echo "${ICON_DUST} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
elif [[ "${WEATHER_MAIN}" = *Mist* ]] || [[ "${WEATHER_MAIN}" = *Haze* ]]; then
  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
else
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
fi

